export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const VERIFIED_TOKEN = "VERIFIED_TOKEN";
export const LOG_OUT = "LOG OUT";
